### ISSUE TITLE
Link to Ultimate Edition

### ISSUE THREAD

**Issue by teacher4711** [portapps/intellij-idea-community-portable#1]
Hi,

could you fix the link to the ultimate edition:
URL: https://portapps.github.io/app/intellij-idea-community-portable/
Given link there (wrong): https://portapps.github.io/app/intellij-ultimate-portable
Correct link: https://portapps.github.io/app/intellij-idea-ultimate-portable/

**Comment by crazy-max** [comment]
Done thanks!
